import cover1 from "@/assets/cover-1.jpg";
import cover2 from "@/assets/cover-2.jpg";
import cover3 from "@/assets/cover-3.jpg";
import cover4 from "@/assets/cover-4.jpg";
import cover5 from "@/assets/cover-5.jpg";
import cover6 from "@/assets/cover-6.jpg";
import cover7 from "@/assets/cover-7.jpg";
import cover8 from "@/assets/cover-8.jpg";
import cover9 from "@/assets/cover-9.jpg";
import cover10 from "@/assets/cover-10.jpg";
import cover11 from "@/assets/cover-11.jpg";
import cover12 from "@/assets/cover-12.jpg";
import cover13 from "@/assets/cover-13.jpg";
import cover14 from "@/assets/cover-14.jpg";

export type ArtistStatus = "viral" | "rising" | "stable" | "drop";
export type LabelId = "6et7" | "back-cata";

export const LABELS: { id: LabelId; name: string; short: string }[] = [
  { id: "6et7", name: "6&7 — Actifs", short: "6&7" },
  { id: "back-cata", name: "6&7 — Back Catalogue", short: "Back cata" },
];

export type Artist = {
  slug: string;
  name: string;
  shortName?: string;
  label: LabelId;
  /** Deezer search term used by the live connector */
  deezerQuery?: string;
  track: string;
  album: string;
  genre: string;
  cover: string;
  accent: string;
  rank: number;
  prev: number;
  streams: string; // monthly listeners
  delta: number;
  momentum: number[];
  status: ArtistStatus;
  country: string;
  city: string;
  saveRate: number; // %
  tourDates: number;
  socialReach: string;
  bio: string;
  insight: string;
};

export const ROSTER: Artist[] = [
  {
    slug: "zazie",
    name: "Zazie",
    label: "6et7",
    deezerQuery: "Zazie",
    track: "Peu Importe",
    album: "Peu Importe",
    genre: "Pop · Chanson",
    cover: cover9,
    accent: "#C8102E",
    rank: 1,
    prev: 2,
    streams: "2.9M",
    delta: 12.4,
    momentum: [40, 46, 52, 58, 66, 74, 82, 92],
    status: "viral",
    country: "FR",
    city: "Paris",
    saveRate: 71,
    tourDates: 22,
    socialReach: "1.6M",
    bio: "Autrice-compositrice icône de la pop francophone, retour attendu avec un single épuré.",
    insight: "« Peu Importe » entre en playlist Hits France — poussée forte sur les 25-44 ans.",
  },
  {
    slug: "jeremy-frerot",
    name: "Jérémy Frerot",
    label: "6et7",
    deezerQuery: "Jeremy Frerot",
    track: "Un homme",
    album: "Frerot",
    genre: "Pop",
    cover: cover10,
    accent: "#5A8DB8",
    rank: 2,
    prev: 5,
    streams: "3.4M",
    delta: 22.8,
    momentum: [22, 28, 36, 44, 54, 64, 72, 80],
    status: "rising",
    country: "FR",
    city: "Bordeaux",
    saveRate: 66,
    tourDates: 18,
    socialReach: "1.4M",
    bio: "Solo après Fréro Delavega, pop atlantique et écriture intime. Album « Frerot » disponible.",
    insight: "« Adieu » et « Un homme » cumulent 4.2M streams cette semaine — pic radio Q2.",
  },
  {
    slug: "skip-the-use",
    name: "Skip the Use",
    label: "6et7",
    deezerQuery: "Skip The Use",
    track: "Silence",
    album: "We Are Good",
    genre: "Rock · Electro",
    cover: cover4,
    accent: "#2DE07A",
    rank: 3,
    prev: 3,
    streams: "1.8M",
    delta: 8.6,
    momentum: [55, 58, 62, 64, 66, 70, 72, 76],
    status: "stable",
    country: "FR",
    city: "Lille",
    saveRate: 68,
    tourDates: 16,
    socialReach: "610K",
    bio: "Retour scénique explosif. Rock électro, énergie live inégalée.",
    insight: "Sync TV en cours sur « Second Love » — regain d'écoute quotidien +18%.",
  },
  {
    slug: "hina",
    name: "Hina",
    label: "6et7",
    deezerQuery: "Hina",
    track: "Fantaisie",
    album: "Fantaisie",
    genre: "Pop",
    cover: cover11,
    accent: "#ED2362",
    rank: 4,
    prev: 8,
    streams: "820K",
    delta: 34.2,
    momentum: [12, 18, 28, 40, 54, 68, 82, 94],
    status: "viral",
    country: "FR",
    city: "Paris",
    saveRate: 73,
    tourDates: 6,
    socialReach: "310K",
    bio: "Nouvelle voix pop française, écriture pointue, direction artistique affirmée.",
    insight: "TikTok : +240K vidéos UGC en 14 jours — la playlist Radar FR ouvre grand.",
  },
  {
    slug: "virgile-martini",
    name: "Virgile Martini",
    label: "6et7",
    deezerQuery: "Virgile Martini",
    track: "Un homme ça pleure pas",
    album: "EP I",
    genre: "Pop alternative",
    cover: cover2,
    accent: "#1E5BFF",
    rank: 5,
    prev: 12,
    streams: "610K",
    delta: 33.7,
    momentum: [8, 14, 22, 32, 44, 56, 68, 78],
    status: "rising",
    country: "FR",
    city: "Paris",
    saveRate: 68,
    tourDates: 5,
    socialReach: "94K",
    bio: "Signé récemment, première vague d'attention critique très positive.",
    insight: "Taux d'ajout playlists user ×3 sur 30j — profil emerging à pousser en priorité.",
  },
  {
    slug: "krisy",
    name: "Krisy",
    label: "6et7",
    deezerQuery: "Krisy",
    track: "Rituel",
    album: "Amer",
    genre: "Rap",
    cover: cover5,
    accent: "#2B2B2B",
    rank: 6,
    prev: 6,
    streams: "1.5M",
    delta: 4.2,
    momentum: [55, 56, 58, 60, 62, 63, 65, 66],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 67,
    tourDates: 11,
    socialReach: "510K",
    bio: "Rap conscient, textures organiques, fidèle à sa ligne.",
    insight: "Croissance lente mais constante — audience qualifiée, taux de complétion 88%.",
  },
  {
    slug: "lubiana",
    name: "Lubiana",
    label: "6et7",
    deezerQuery: "Lubiana",
    track: "Farafina Mousso",
    album: "Farafina Mousso",
    genre: "Soul · World",
    cover: cover14,
    accent: "#4B2D7A",
    rank: 7,
    prev: 9,
    streams: "740K",
    delta: 11.8,
    momentum: [30, 34, 38, 44, 50, 56, 62, 68],
    status: "rising",
    country: "FR",
    city: "Paris",
    saveRate: 70,
    tourDates: 12,
    socialReach: "220K",
    bio: "Chanteuse et kora, projet soul-world profondément incarné.",
    insight: "Belle traction Europe du Nord — la piste sync docu à confirmer.",
  },
  {
    slug: "lancelot",
    name: "Lancelot",
    label: "6et7",
    deezerQuery: "Lancelot",
    track: "Un homme seul",
    album: "Premier tour",
    genre: "Pop · Folk",
    cover: cover13,
    accent: "#E07B2D",
    rank: 8,
    prev: 14,
    streams: "540K",
    delta: 28.4,
    momentum: [12, 18, 26, 34, 44, 56, 66, 76],
    status: "rising",
    country: "FR",
    city: "Lyon",
    saveRate: 63,
    tourDates: 24,
    socialReach: "210K",
    bio: "Pop folk lumineuse, mélodies imparables, présent sur toutes les scènes émergentes.",
    insight: "Discover Weekly Spotify génère 38% des nouveaux auditeurs — moment charnière.",
  },
  {
    slug: "kimberose",
    name: "Kimberose",
    label: "6et7",
    deezerQuery: "Kimberose",
    track: "Back on My Feet",
    album: "Out",
    genre: "Soul",
    cover: cover7,
    accent: "#7A2DE0",
    rank: 9,
    prev: 7,
    streams: "1.1M",
    delta: 3.2,
    momentum: [58, 58, 60, 60, 62, 62, 64, 64],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 71,
    tourDates: 9,
    socialReach: "380K",
    bio: "Voix soul indéniable, base fanbase solide en France et Benelux.",
    insight: "Save rate 71% — l'album complet reste sous-poussé sur Apple Music.",
  },
  {
    slug: "nabil-harlow",
    name: "Nabil Harlow",
    label: "6et7",
    deezerQuery: "Nabil Harlow",
    track: "Solstice",
    album: "Harlow",
    genre: "R&B",
    cover: cover6,
    accent: "#E2A8DA",
    rank: 10,
    prev: 10,
    streams: "480K",
    delta: 6.1,
    momentum: [40, 44, 48, 52, 55, 58, 60, 64],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 71,
    tourDates: 6,
    socialReach: "160K",
    bio: "R&B francophone, production soyeuse, voix de velours.",
    insight: "Save rate élevé — signal fort pour push playlist R&B éditorial.",
  },
  {
    slug: "laura-ferre",
    name: "Laura Ferré",
    label: "6et7",
    deezerQuery: "Laura Ferre",
    track: "Encore",
    album: "Premiers pas",
    genre: "Chanson · Pop",
    cover: cover8,
    accent: "#2DA89A",
    rank: 11,
    prev: 11,
    streams: "310K",
    delta: 5.4,
    momentum: [30, 32, 34, 36, 40, 42, 46, 48],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 62,
    tourDates: 4,
    socialReach: "88K",
    bio: "Co-exploitation avec PlayTwo. Voix qui monte, écriture personnelle.",
    insight: "Cas particulier data — accès Believe Backstage individuel à consolider.",
  },
  {
    slug: "marie-flore",
    name: "Marie-Flore",
    label: "back-cata",
    deezerQuery: "Marie-Flore",
    track: "Braquage",
    album: "Braquage",
    genre: "Pop indé",
    cover: cover3,
    accent: "#9B6B43",
    rank: 12,
    prev: 12,
    streams: "260K",
    delta: 1.8,
    momentum: [40, 40, 42, 42, 44, 44, 46, 46],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 64,
    tourDates: 3,
    socialReach: "72K",
    bio: "Back catalogue vivant. Pop indé, base fan fidèle.",
    insight: "Sync TV régulier — potentiel de relance sur une réédition.",
  },
  {
    slug: "vanille",
    name: "Vanille",
    label: "back-cata",
    deezerQuery: "Vanille",
    track: "Soleil bleu",
    album: "La Clairière",
    genre: "Folk · Pop",
    cover: cover12,
    accent: "#2B2B2B",
    rank: 13,
    prev: 13,
    streams: "180K",
    delta: 0.6,
    momentum: [38, 38, 40, 40, 40, 42, 42, 42],
    status: "stable",
    country: "CA",
    city: "Montréal",
    saveRate: 60,
    tourDates: 2,
    socialReach: "44K",
    bio: "Folk pop québécoise, tendresse et précision.",
    insight: "Audience Québec stable — leviers France encore inexploités.",
  },
  {
    slug: "sheng",
    name: "Sheng",
    label: "back-cata",
    deezerQuery: "Sheng",
    track: "Nord",
    album: "Traits",
    genre: "Rap",
    cover: cover1,
    accent: "#ED2362",
    rank: 14,
    prev: 15,
    streams: "220K",
    delta: 2.9,
    momentum: [30, 32, 34, 34, 36, 38, 38, 40],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 66,
    tourDates: 1,
    socialReach: "58K",
    bio: "Écriture rap dense, back catalogue à valoriser.",
    insight: "Streams stables — opportunité relance via feat back cata.",
  },
  {
    slug: "oboy",
    name: "Oboy",
    label: "back-cata",
    deezerQuery: "Oboy",
    track: "OKLM",
    album: "OKLM",
    genre: "Rap",
    cover: cover4,
    accent: "#2DE07A",
    rank: 15,
    prev: 14,
    streams: "410K",
    delta: -3.2,
    momentum: [55, 52, 50, 50, 48, 46, 46, 44],
    status: "drop",
    country: "FR",
    city: "Paris",
    saveRate: 61,
    tourDates: 0,
    socialReach: "190K",
    bio: "Back catalogue rap. Streams solides, activité récente limitée.",
    insight: "Léger déclin — timing intéressant pour une remasterisation ou best-of.",
  },
];

export const getArtist = (slug: string) => ROSTER.find((a) => a.slug === slug);
