import cover1 from "@/assets/cover-1.jpg";
import cover2 from "@/assets/cover-2.jpg";
import cover3 from "@/assets/cover-3.jpg";
import cover4 from "@/assets/cover-4.jpg";
import cover5 from "@/assets/cover-5.jpg";
import cover6 from "@/assets/cover-6.jpg";
import cover7 from "@/assets/cover-7.jpg";
import cover8 from "@/assets/cover-8.jpg";
import cover9 from "@/assets/cover-9.jpg";
import cover10 from "@/assets/cover-10.jpg";
import cover11 from "@/assets/cover-11.jpg";
import cover12 from "@/assets/cover-12.jpg";
import cover13 from "@/assets/cover-13.jpg";
import cover14 from "@/assets/cover-14.jpg";

export type ArtistStatus = "viral" | "rising" | "stable" | "drop";

export type Artist = {
  slug: string;
  name: string;
  shortName?: string;
  track: string;
  album: string;
  genre: string;
  cover: string;
  accent: string;
  rank: number;
  prev: number;
  streams: string; // monthly listeners
  delta: number;
  momentum: number[];
  status: ArtistStatus;
  country: string;
  city: string;
  saveRate: number; // %
  tourDates: number;
  socialReach: string;
  bio: string;
  insight: string;
};

export const ROSTER: Artist[] = [
  {
    slug: "mylene-farmer",
    name: "Mylène Farmer",
    track: "L'Âme dans l'Eau",
    album: "Nevermore II",
    genre: "Pop · Synth",
    cover: cover9,
    accent: "#C8102E",
    rank: 1,
    prev: 2,
    streams: "8.4M",
    delta: 14.2,
    momentum: [40, 48, 52, 58, 64, 72, 84, 96],
    status: "viral",
    country: "FR",
    city: "Paris",
    saveRate: 72,
    tourDates: 14,
    socialReach: "5.1M",
    bio: "Icône absolue de la pop francophone. Le stade de France attend le retour de Nevermore.",
    insight: "Le single dépasse 1.2M de streams quotidiens — accélération nette sur Paris, Bruxelles, Montréal.",
  },
  {
    slug: "julien-clerc",
    name: "Julien Clerc",
    track: "Les jours heureux",
    album: "Juste un peu de toi",
    genre: "Chanson",
    cover: cover3,
    accent: "#9B6B43",
    rank: 2,
    prev: 1,
    streams: "1.9M",
    delta: -2.4,
    momentum: [80, 78, 74, 70, 68, 64, 60, 58],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 64,
    tourDates: 32,
    socialReach: "780K",
    bio: "55 ans de carrière, une tournée des Zéniths qui affiche complet.",
    insight: "Catalogue très demandé sur l'écoute familiale — playlists chanson en hausse de 18%.",
  },
  {
    slug: "matthieu-chedid",
    name: "Matthieu Chédid",
    shortName: "-M-",
    track: "Lamomali Reverie",
    album: "Rêvalité",
    genre: "Pop · World",
    cover: cover12,
    accent: "#2B2B2B",
    rank: 3,
    prev: 4,
    streams: "2.6M",
    delta: 9.6,
    momentum: [30, 38, 44, 52, 58, 62, 68, 74],
    status: "rising",
    country: "FR",
    city: "Paris",
    saveRate: 70,
    tourDates: 22,
    socialReach: "1.1M",
    bio: "Guitar wizard. Collaborations avec Toumani Diabaté, Sidi Touré, Vanessa Paradis.",
    insight: "Les sessions live de Lamomali tournent fort sur YouTube — +38% de watch time.",
  },
  {
    slug: "jeremy-frerot",
    name: "Jérémy Frerot",
    track: "Vagabond",
    album: "Meilleure vie",
    genre: "Pop",
    cover: cover10,
    accent: "#5A8DB8",
    rank: 4,
    prev: 6,
    streams: "3.1M",
    delta: 22.8,
    momentum: [22, 28, 36, 44, 54, 64, 72, 80],
    status: "rising",
    country: "FR",
    city: "Bordeaux",
    saveRate: 66,
    tourDates: 18,
    socialReach: "1.4M",
    bio: "Solo après Fréro Delavega. Pop atlantique, écriture intime.",
    insight: "Forte traction TikTok sur le refrain — recommandation : push campagne France/Belgique.",
  },
  {
    slug: "suzane",
    name: "Suzane",
    track: "Toï Toï",
    album: "Caméo",
    genre: "Electro-pop",
    cover: cover11,
    accent: "#ED2362",
    rank: 5,
    prev: 9,
    streams: "1.7M",
    delta: 41.5,
    momentum: [10, 16, 24, 34, 48, 62, 80, 96],
    status: "viral",
    country: "FR",
    city: "Avignon",
    saveRate: 74,
    tourDates: 28,
    socialReach: "640K",
    bio: "Performeuse-conteuse, scène habitée, écriture politique.",
    insight: "Entrée Top 50 Viral France — pic d'engagement après le passage TV.",
  },
  {
    slug: "klon",
    name: "KLON",
    track: "Béton armé",
    album: "Génération KLON",
    genre: "Rap",
    cover: cover4,
    accent: "#2DE07A",
    rank: 6,
    prev: 12,
    streams: "2.3M",
    delta: 36.0,
    momentum: [18, 24, 32, 44, 56, 68, 78, 88],
    status: "rising",
    country: "FR",
    city: "Paris",
    saveRate: 69,
    tourDates: 9,
    socialReach: "820K",
    bio: "Nouvelle vague rap français, plume incisive.",
    insight: "Audience 18-24 dominante — la fenêtre est ouverte pour un featuring international.",
  },
  {
    slug: "nabil-harlow",
    name: "Nabil Harlow",
    track: "Solstice",
    album: "Harlow",
    genre: "R&B",
    cover: cover7,
    accent: "#7A2DE0",
    rank: 7,
    prev: 7,
    streams: "1.2M",
    delta: 6.1,
    momentum: [40, 44, 48, 52, 55, 58, 60, 64],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 71,
    tourDates: 6,
    socialReach: "420K",
    bio: "R&B francophone, production soyeuse, voix de velours.",
    insight: "Save rate élevé (71%) — signal fort pour pousser l'album complet en playlist editorial.",
  },
  {
    slug: "krisy",
    name: "Krisy",
    track: "Rituel",
    album: "Amer",
    genre: "Rap",
    cover: cover5,
    accent: "#2B2B2B",
    rank: 8,
    prev: 8,
    streams: "1.5M",
    delta: 4.2,
    momentum: [55, 56, 58, 60, 62, 63, 65, 66],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 67,
    tourDates: 11,
    socialReach: "510K",
    bio: "Rap conscient, textures organiques, fidèle à sa ligne.",
    insight: "Croissance lente mais constante — audience qualifiée, taux de complétion 88%.",
  },
  {
    slug: "lancelot",
    name: "Lancelot",
    track: "Le tour du monde",
    album: "Premier tour",
    genre: "Pop · Folk",
    cover: cover13,
    accent: "#E07B2D",
    rank: 9,
    prev: 14,
    streams: "920K",
    delta: 28.4,
    momentum: [12, 18, 26, 34, 44, 56, 66, 76],
    status: "rising",
    country: "FR",
    city: "Lyon",
    saveRate: 63,
    tourDates: 24,
    socialReach: "210K",
    bio: "Nouvel artiste #NP, pop folk lumineuse, mélodies imparables.",
    insight: "Effet 'découverte' Spotify — Discover Weekly génère 38% des nouveaux auditeurs.",
  },
  {
    slug: "aurelien-vivos",
    name: "Aurélien Vivos",
    track: "Tout brûler",
    album: "Vivos",
    genre: "Pop urbaine",
    cover: cover6,
    accent: "#E2A8DA",
    rank: 10,
    prev: 10,
    streams: "780K",
    delta: 2.1,
    momentum: [50, 52, 54, 55, 56, 58, 60, 60],
    status: "stable",
    country: "FR",
    city: "Marseille",
    saveRate: 60,
    tourDates: 7,
    socialReach: "180K",
    bio: "Auteur-compositeur, plume cinématographique.",
    insight: "Forte écoute en voiture — opportunité radio FM en Q1.",
  },
  {
    slug: "waxx-c-cole",
    name: "Waxx & C. Cole",
    track: "Wild Roads",
    album: "Twin Peaks Sessions",
    genre: "Blues · Rock",
    cover: cover8,
    accent: "#2DA89A",
    rank: 11,
    prev: 11,
    streams: "640K",
    delta: 1.4,
    momentum: [48, 50, 50, 52, 53, 54, 54, 55],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 65,
    tourDates: 19,
    socialReach: "150K",
    bio: "Duo guitare-voix, héritage blues, énergie scène.",
    insight: "Audience US grandissante — 22% du catalogue lu depuis l'Amérique du Nord.",
  },
  {
    slug: "virgile-martini",
    name: "Virgile Martini",
    track: "À contre-jour",
    album: "EP I",
    genre: "Pop alternative",
    cover: cover2,
    accent: "#1E5BFF",
    rank: 12,
    prev: 18,
    streams: "510K",
    delta: 33.7,
    momentum: [8, 14, 22, 32, 44, 56, 68, 78],
    status: "rising",
    country: "FR",
    city: "Paris",
    saveRate: 68,
    tourDates: 5,
    socialReach: "92K",
    bio: "Signé en 2025. Première vague d'attention critique très positive.",
    insight: "Profil emerging à surveiller — taux d'ajout playlists user x3 sur 30j.",
  },
  {
    slug: "era",
    name: "ERA",
    track: "Ameno (Reborn)",
    album: "The Mass — 25",
    genre: "New age · Choral",
    cover: cover14,
    accent: "#4B2D7A",
    rank: 13,
    prev: 13,
    streams: "1.1M",
    delta: 5.8,
    momentum: [60, 60, 62, 62, 64, 64, 66, 66],
    status: "stable",
    country: "FR",
    city: "Paris",
    saveRate: 58,
    tourDates: 4,
    socialReach: "240K",
    bio: "Projet d'Eric Lévi, chorales monumentales, classique de la scène mondiale.",
    insight: "Catalogue stable, regain sur sync TV/cinéma — 4 placements ce trimestre.",
  },
  {
    slug: "eos-records",
    name: "EOS Records",
    track: "Roster Sampler Vol. 3",
    album: "EOS — Compilation",
    genre: "Label · Multi",
    cover: cover1,
    accent: "#ED2362",
    rank: 14,
    prev: 15,
    streams: "420K",
    delta: 7.3,
    momentum: [30, 32, 36, 38, 42, 46, 50, 54],
    status: "rising",
    country: "FR",
    city: "Paris",
    saveRate: 55,
    tourDates: 0,
    socialReach: "75K",
    bio: "Label associé à #NP — développement de nouveaux talents francophones.",
    insight: "Compilation lancée la semaine dernière — bon démarrage sur les playlists Indie FR.",
  },
];

export const getArtist = (slug: string) => ROSTER.find((a) => a.slug === slug);
